### ISSUE TITLE
ParallelSSHClient.copy_file never throws exception for me

### ISSUE THREAD

**Issue by bexp** [pkittenis/parallel-ssh#62]
even if I try to copy file into some dummy host or unreachable I don't see an exception

**Comment by bexp** [comment]
I think it would be more consistent for client.copy_file to have same return output as client.run_command

**Comment by pkittenis** [comment]
Hi there,

Thank you for the interest. Is there example code that reproduces this? Works as expected as far as I can see, eg

```
client = ParallelSSHClient(['dummy_host'], num_retries=1)
for cmd in client.copy_file("test", "test"):
    cmd.get()

UnknownHostException: ('Unknown host %s - %s - retry %s/%s', 'dummy_host', 'Name or service not known', 1, 1)
```

[`copy_file` documentation](http://parallel-ssh.readthedocs.io/en/latest/pssh_client.html#pssh.pssh_client.ParallelSSHClient.copy_file) says it returns greenlets (and does not raise connection exceptions) so client code needs to `.get` the greenlets to wait for completion + raise exceptions as above or `client.pool.join()` to wait for completion and, optionally, `.get` the completed greenlets to raise any exceptions from them.

If neither the pool is joined nor the greenlets waited on, they are not executed at all and get no chance to trigger an exception - that is expected behaviour.

Will update docs with some examples of this though.

As for having `copy_file` return same output as `run_command`, that is not feasible. SFTP is a different protocol and provides none of the things returned by `run_command` other than the greenlet for the command itself. It instead returns the greenlets directly to let the programmer handle them.

**Comment by pkittenis** [comment]
Closing - works as expected. Can be re-opened if code can be provided to reproduce an issue.

**Comment by bexp** [comment]
ok thanks for explaining, one question though, if I want to remove erroneous host from the client 
after I got an exception how do I do that ?

**Comment by pkittenis** [comment]
Can remove it from host list, eg:

```
   bad_host = client.hosts.index('bad_host')
   if bad_host:
       del client.hosts[bad_host]
```
