### ISSUE TITLE
Missing OpenSSH config breaks client

### ISSUE THREAD

**Issue by sergani** [pkittenis/parallel-ssh#63]
Hello,

I've pulled and edited the parallel_commands.py example script, to connect to a host of mine (localhost returns the same issue), and I get the following error when I run the script:
```python
No handlers could be found for logger "pssh"
Traceback (most recent call last):
  File "file.py", line 13, in <module>
    output.append(client.run_command(cmd, stop_on_errors=True))
  File "/Users/sergani/myproject/lib/python2.7/site-packages/pssh/pssh_client.py", line 520, in run_command
    raise ex
TypeError: 'NoneType' object is not iterable
```
Thoughts? :-)

Thanks
//M

**Comment by pkittenis** [comment]
My thoughts are

 * Example code was edited to enable `stop_on_errors`
 * There is probably an exception connecting which is then causing the above exception
 * When raising issues, need to show code that replicates the issue

Since the example file was edited and code to replicate an issue with library is not shown, not clear what is being reported by this issue.

Can edit the script to re-disable stop on errors and print out output, that should tell you what exception is happening.

Unless there is some code that can be used to replicate an issue, will be closing this and ask you to raise questions on usage on the [mailing group](https://groups.google.com/forum/#!forum/parallelssh), thanks.

**Comment by pkittenis** [comment]
Thanks for raising :+1: 

Have hidden the `0.92.0` release in pypi to stop others from encountering this. Any other version will work including latest `0.92.1` which includes a fix for this.

**Comment by sergani** [comment]
Glad to have helped :-)

Thanks
//M
